### ISSUE TITLE
Configure RemoteHttpForward in config file

### ISSUE THREAD

**Issue by anengineerdude** [Azure/azure-relay-bridge#83]
There does not seem to be an option to configure the "-H" option to setup Http forward in the config file.

Add an example or support to configure the Http Forward in the config files.

**Comment by paveliak** [comment]
Did you try `Http: true`? I would expect it to do what you need.

```
RemoteForward :
   - RelayName: "meow"
     Http: true
```

**Comment by linckez** [comment]
After some digging I found that you have to specify the HTTP binding in the config file, to get the same behaviour as when using `-H`. 

```yaml
# HTTPS Example (ssl)
# This forwards an onprem API (https) on port 443, AND creates a binding to 443 on the below.
# This is equal to using the -H (remote http forwarding) flag in the azbridge command line.
# Source Address: https://example.corp.lego.com/api/v1/docs
# Destination Address: https://my-onprem-relay.servicebus.windows.net/api-relay/docs
- RelayName: api-relay
  Host: example.corp.lego.com
  HostPort: 443
  Http: true
  Bindings:
    - Host: example.corp.lego.com
      HostPort: 443
      #PortName: http
      PortName: https
      Http: true
      # Insecure: false
      Insecure: true # set to true to ignore ssl cert failures
      Path: /api/v1/
```
